export { ReactComponent as HomeIcon } from './home.svg'
export { ReactComponent as ManageIcon } from './manage_accounts.svg'
export { ReactComponent as ErrorIcon } from './error.svg'
export { ReactComponent as HeartbeatIcon } from './heartbeat.svg'
export { ReactComponent as LogoutIcon } from './logout.svg'
